tee backend-ontap-nas.yaml <<EOF

apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-ontap-nas-secret
type: Opaque
stringData:
  username: admin #cluster 계정
  password: Netapp1! #cluster 계정 패스워드
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.101 #cluster-mgmt IP
  dataLIF: 192.168.0.150 #vserser data-lif
  backendName: ontap-backend
  svm: trident
  limitVolumeSize: 30Gi #storage size
  credentials:
    name: backend-tbc-ontap-nas-secret
  storagePrefix: trident_
  defaults:
    spaceReserve: none
    snapshotPolicy: none
